# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b96886b80753a9547978ec6a9aedeeee8ec345cbfd81bcdf42cbb5f83f47ed62ead9dce6812ba19a1db18cf8b9ffb6a0e58eb1662109bbe36015b8fc27beb5

test:
  secret_key_base: 3312696eb0138072455345a4c5854a6ad52b5e70a2435add380dcbfb00324f21eb4cf9dda60e08f288acebb196852a3920a2b5582b0ef30860cafbd0e9c417e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
